ldap:
  bind:
    user: cn=rla,ou=services,dc=ldap,dc=vandelayindustries,dc=com
    password: ldap_password
  domain: vandelayindustries.com
  helpdesk: helpdesk
  mail:
    user: rla_mail
    password: mail_password
  port: 636
  search_base:
    groups: ou=groups,dc=ldap,dc=vandelayindustries,dc=com
    users: ou=users,dc=ldap,dc=vandelayindustries,dc=com
