domain: "vandelayindustries.com"
ldap_bind_user: "cn=rla,ou=services,dc=ldap,dc=vandelayindustries,dc=com"
ldap_bind_password: "ldap_password"
ldap_port: "636"
ldap_search_base_groups: "ou=groups,dc=ldap,dc=vandelayindustries,dc=com"
ldap_search_base_users: "ou=users,dc=ldap,dc=vandelayindustries,dc=com"
mail_helpdesk: "helpdesk"
mail_user: "rla_mail"
mail_password: "mail_password"
