default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: rla_development

test:
  <<: *default
  database: rla_test

production:
  <<: *default
  database: rla_production
  username: rla_production
  password: <%= ENV['DB_PASS'] %>
