## Authorizations

authorizations: &AUTHORIZATIONS
  allow_unauthenticated_bind: false
  group_base: <%= Figaro.env.ldap_search_base_groups %>

## Environment

development:
  host: ldap.<%= Figaro.env.domain %>
  port: <%= Figaro.env.ldap_port %>
  attribute: mail
  base: <%= Figaro.env.ldap_search_base_users %>
  admin_user: <%= Figaro.env.ldap_bind_user %>
  admin_password: <%= Figaro.env.ldap_bind_password %>
  ssl: simple_tls
  # <<: *AUTHORIZATIONS

production:
  host: ldap.<%= Figaro.env.domain %>
  port: <%= Figaro.env.ldap_port %>
  attribute: mail
  base: <%= Figaro.env.ldap_search_base_users %>
  admin_user: <%= Figaro.env.ldap_bind_user %>
  admin_password: <%= Figaro.env.ldap_bind_password %>
  ssl: simple_tls
  # <<: *AUTHORIZATIONS
